name: Terraform
on:
  release:
    types: [published]

env:
  DIR: prod
  AWS_ACCESS_KEY: ${{ secrets.PROD_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}

jobs:
  check-format:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff

  validations:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform Cloud login
        run: .github/workflows/scripts/terraform-login.sh
      - name: Terraform Init
        run: terraform init -upgrade
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan -out=plan.out
      - name: Terraform Apply
        run: terraform apply plan.out
